import { FC } from "react"
import { Metadata } from "next"
import RandomPhoto from "@/components/random-photo"
import Link from "@/components/ui/link"
import SectionTitle from "@/components/ui/section-title"
import { siteConfig } from "@/config/site"

export const metadata: Metadata = {
  title: "whoami | Yash Agarwal",
  description: "Learn about me and what I do.",
  alternates: {
    canonical: `${siteConfig.url}/whoami`,
    types: {
      "application/rss+xml": [
        { url: "rss.xml", title: "RSS Feed for yashagarwal.in" },
        { url: "atom.xml", title: "Atom Feed for yashagarwal.in" },
      ],
    },
  },
}

const Page: FC = () => {
  return (
    <>
      <SectionTitle data={null} title="work" />
      <section className="prose prose-lg prose-article">
        <p>
          I am a enthusiastic software developer with a knack for backend
          development. I&apos;ve got my hands dirty in Python, Golang, and C++.
          I have mainly worked in cybersecurity domain in my career including
          things like web-application penetration testing and writing code for
          both POCs and highly scalable commercial security products.
          <br />
          <br />
          What sets me apart? I am not just about what&apos;s already in the
          toolkit. A relentless commitment to continuous learning and
          adaptability. I am always ready to dive into the latest, adapt and
          turn challenges into victory.
        </p>

        <p>Here&apos;s a summary of my work so far -</p>
        <div>
          <h2 className="my-2 text-2xl">Netskope</h2>
          <h4 className="text-base font-normal text-gray-700">
            Sr. Software Engineer, 2024-Present
          </h4>
          <p>
            As I transitioned to a senior role in Netskope, I started working on
            the next-gen implementation of the CASB API product, while also
            maintaining the two crucial apps from the legacy product, ensuring a
            smooth transition to the next-gen implementations.
          </p>

          <h4 className="text-base font-normal text-gray-700">
            Software Engineer II, 2022-2024
          </h4>
          <p>
            I joined the API Data Protection Team in 2022. Since then, I have
            grown in the team to own end-to-end pipeline for two of the app
            implementations.
          </p>
          <ul>
            <li>
              Implemented a system to enable migration of existing customers to
              the next-gen product without any downtime.
            </li>
            <li>
              Took initiative to improve the file listing performance for one of
              the apps and implemented check-pointing logic to prevent retrying
              duplicate tasks on any API rate limiting.
            </li>
          </ul>
        </div>
        <div>
          <h2 className="my-2 text-2xl">Cisco Systems</h2>
          <h4 className="text-base font-normal text-gray-700">
            Software Engineer I and II, 2018-2021
          </h4>
          <ul>
            <li>
              Did an analysis of Cisco FTD&apos;s layer-7 detection capabilities
              against the open-source WAF ModSecurity and provided suggestions
              to improve Snort&apos;s detection capabilities.
            </li>
            <ul>
              <li>
                Used automated and manual pentesting methodologies to generate
                the traffic to these tools
              </li>
              <li>
                Standardised the logs generated by these tools and used
                log-correlation to compare the efficacy and performance of FTD
              </li>
              <li>
                Orchestrated and managed the entire supporting infrastructure on
                AWS.
              </li>
            </ul>
            <li>
              Later joined Snort team to help improve its layer-7 detection
              capabilities.
            </li>
            <ul>
              <li>
                Implemented Portscan feature for FTD platforms by moving it to
                layer-2 (ASA) from layer-4 (Snort)
              </li>
            </ul>
            <li>
              Worked on implementing monitoring capabilities in Cisco Secure
              Firewall Cloud Native (SFCN) using open-source Prometheus, Grafana
              and Telegraf stack using Helm charts.
            </li>
          </ul>
        </div>
      </section>
    </>
  )
}

export default Page
